---

  logging:
    level:
      org.springframework: INFO

  server:
    port: 9125

  spring:
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost/psychological-testing
      username: postgres
      password: postgres
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: update
